### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by benhager** [podhrmic/JSBSim-Matlab#2]
Hey,
Where you able to get this working and get an aircraft model running in Simulink?
Thanks!
-Ben

**Comment by bcoconni** [comment]
Hi @podhrmic,

Thanks to the work of @sthelia, we are almost ready to merge the PR JSBSim-Team/JSBSim#445 which is based on the work you've published in this repo (podhrmic/JSBSim-Matlab). Since you did not provide a license to your repo, we'd need your formal approval to publish the files provided by the PR JSBSim-Team/JSBSim#445 mentioned above under an open source license (see details in the PR).

Would you mind granting your permission for us to use your code ? If so, please drop a message in the PR JSBSim-Team/JSBSim#445 (a short message such as 'You have my permission.' will do).

Thanks.

**Comment by podhrmic** [comment]
Done. Once you merge @sthelia 's work, I will gladly archive this repo.
